apiVersion: v1
appVersion: 0.1.0
description: A Helm chart for azure-scheduled-events
engine: gotpl
home: https://github.com/giantswarm/azure-scheduled-events
icon: https://some.domain.com/logo.png
name: azure-scheduled-events
sources:
  - https://github.com/giantswarm/azure-scheduled-events
version: [[ .Version ]]
